/**
 * YieldOptimizer — auto-compounding yield optimizer across DeFi protocols
 * Monitors APY, rebalances, harvests rewards, manages risk
 */

import { BaseSDK, type BaseSDKConfig } from "@jellychain/sdk-core";

export interface YieldOpportunity { protocol: string; chainId: number; pool: string; token: string; apy: number; tvl: number; rewardTokens: string[]; riskScore: number; lastHarvest: number }
export interface YieldPosition { protocol: string; pool: string; deposited: bigint; rewards: bigint; apy: number; depositedAt: number; lastCompounded: number }
export interface OptimizerConfig extends BaseSDKConfig { scanInterval?: number; minApy?: number; maxRisk?: number; autoCompound?: boolean; compoundThreshold?: number }
export class YieldOptimizer extends BaseSDK { private opportunities: YieldOpportunity[] = []; private positions: YieldPosition[] = []; constructor(config: OptimizerConfig) { super(config, "YieldOptimizer"); } async scanOpportunities(): Promise<YieldOpportunity[]> { this.opportunities = [{ protocol: "aave", chainId: 1, pool: "USDC", token: "USDC", apy: 4.5, tvl: 500000000, rewardTokens: ["AAVE"], riskScore: 15, lastHarvest: Date.now() }, { protocol: "compound", chainId: 1, pool: "USDC", token: "USDC", apy: 3.8, tvl: 300000000, rewardTokens: ["COMP"], riskScore: 12, lastHarvest: Date.now() }, { protocol: "curve", chainId: 1, pool: "3pool", token: "USDC", apy: 6.2, tvl: 800000000, rewardTokens: ["CRV", "CVX"], riskScore: 25, lastHarvest: Date.now() }, { protocol: "convex", chainId: 1, pool: "Curve stETH", token: "ETH", apy: 3.5, tvl: 1200000000, rewardTokens: ["CRV", "CVX"], riskScore: 20, lastHarvest: Date.now() }, { protocol: "lido", chainId: 1, pool: "stETH", token: "ETH", apy: 3.2, tvl: 15000000000, rewardTokens: ["LDO"], riskScore: 10, lastHarvest: Date.now() }]; return this.opportunities; } getBestOpportunity(minApy = 0, maxRisk = 50): YieldOpportunity | undefined { return this.opportunities.filter(o => o.apy >= minApy && o.riskScore <= maxRisk).sort((a, b) => b.apy - a.apy)[0]; } getAllOpportunities(): YieldOpportunity[] { return [...this.opportunities]; } addPosition(protocol: string, pool: string, amount: bigint, apy: number): YieldPosition { const pos: YieldPosition = { protocol, pool, deposited: amount, rewards: 0n, apy, depositedAt: Date.now(), lastCompounded: Date.now() }; this.positions.push(pos); return pos; } getPositions(): YieldPosition[] { return [...this.positions]; } getTotalDeposited(): bigint { return this.positions.reduce((s, p) => s + p.deposited, 0n); } getWeightedAverageApy(): number { const total = this.getTotalDeposited(); if (total === 0n) return 0; return this.positions.reduce((s, p) => s + Number(p.deposited) * p.apy, 0) / Number(total); } async estimateRewards(position: YieldPosition, days = 30): Promise<bigint> { const dailyRate = position.apy / 100 / 365; return BigInt(Math.floor(Number(position.deposited) * dailyRate * days)); } shouldCompound(position: YieldPosition, thresholdUsd = 100): boolean { const estRewards = Date.now() - position.lastCompounded > 86400000; return estRewards && position.rewards > 0n; } getRebalanceRecommendation(currentAllocations: Record<string, number>): { from: string; to: string; amount: bigint; reason: string }[] { const recommendations: { from: string; to: string; amount: bigint; reason: string }[] = []; const best = this.getBestOpportunity(3, 30); if (!best) return recommendations; recommendations.push({ from: "idle", to: best.pool, amount: 0n, reason: `${best.pool} on ${best.protocol} offers ${best.apy}% APY` }); return recommendations; } }
